### PR TITLE
File format error handling exception

### LINKED ISSUE #10: File Load fails if the curve name contains only numbers
When selecting a file, if the curve name contains only numbers and no letters, then an uncaught exception is raised : 

`AttributeError: 'float' object has no attribute 'upper'`

This occurs in _backend.py in the on_file_load method, where the unique curves are gathered from the first column.  This should accept a curve which is digits only.

### LINKED ISSUE #11: Missing units error is unhandled
In the file load dialog, if a file is loaded which does not contain any units in the second column, then an uncaught exception is raised : 

`TypeError: 'numpy.float64' object is not iterable`

This should be handled and an error dialog raised to indicate that the variables must contain units.

### PR DESCRIPTION
**Pull request by Flaminator89**
This PR fixes a couple of uncaught exceptions that could occur if the file format loaded was not correct.  Specifically, if the variables [had no units](https://github.com/seeq12/seeq-plot-curve/issues/11), or if the names of the curves were numeric _only_ and did [not contain any non numeric characters](https://github.com/seeq12/seeq-plot-curve/issues/10).  I also reverted the pagination for the table so it allows the user to select how many rows should be present in the table.

Primary Reviewer : @ehsanshahidi  

closes #10 
closes #11

### CODE REVIEW

File: docs/_static/documentation_options.js [hunk 1]
```diff
@@ -1,6 +1,6 @@
 var DOCUMENTATION_OPTIONS = {
     URL_ROOT: document.getElementById("documentation_options").getAttribute('data-url_root'),
-    VERSION: '0.1.0',
+    VERSION: '0.1.1',
```
Comment (ehsanshahidi) [inline docs/_static/documentation_options.js:3]: Just curious, what are our rules for incrementing versions? What change constitutes a 1.0.0 vs 0.2.1 vs 0.1.2 from 0.1.1?

File: docs/objects.inv [hunk 2]
```diff
@@ -1,5 +1,5 @@
...
-# Version: 0.1.0
+# Version: 0.1.1
 # The remainder of this file is compressed using zlib.
 xڅ�AN!E�
��[�.FM&1�rBC�&���)
g�5��'�� �wԫ��=)o���̍	Z�RWx5ь�B;R�߄
+�R	
�y�QT#������QXGS�L8���$�;Gwimf�v�^u�AR��m8b�A��
�?���B���/���e#Y�%��/�ƫֈ@��G荂8������׎�68��#����h�3My�
A-zڊ��y��^Y)�r�ə�Ce�9�r���f���
```
Comment (ehsanshahidi) [inline docs/objects.inv:5]: I am not familiar with how documentation is build, but what is this seemingly binary line here?

File: docs/_static/documentation_options.js (hunk 1 above)
Comment (Flaminator89) [reply docs/_static/documentation_options.js:3]: Good question.  Seth might have more information as to how we are doing that with our AR apps.  I've seen the first used for breaking updates... the second for features and the third for bug fixes.  Since this PR is only bugfixes/patches, that is the reason why I've made it just an increment of the last digit.

**Review by ehsanshahidi — APPROVED** [review]
Exploratory tests: Checked out the code, created a whl file, ran the deployment notebook on a datalab project container. Gave number-only curve names, no units, and unnamed dependent variables. They all work. Code looks good too.
